## Routes
---
/:                                     { controller: default, action: index }

/signup:                               { controller: signup, action: signup, authz: guest }
/signup/confirm:                       { controller: signup, action: confirm }

/login:                                { controller: auth, action: login, authz: guest }
/login/*:                              { controller: auth, action: login-with, args: [ $2 ], authz: guest }
/logout:                               { controller: auth, action: logout, authz: user }
/forgot-password:                      { controller: auth, action: forgot-password, authz: guest }
/reset-password +GET:                  { controller: auth, action: show-reset-password, authz: guest }
/reset-password +POST:                 { controller: auth, action: reset-password, authz: guest }

/settings +GET:                        { controller: user, action: show-edit, authz: user }
/settings +POST:                       { controller: user, action: edit, authz: user }
/settings/edit-password +GET:          { controller: user, action: show-edit-password, authz: user }
/settings/edit-password +POST:         { controller: user, action: edit-password, authz: user }
/settings/delete +POST:                { controller: user, action: delete, authz: user }
/good-bye:                             { controller: user, action: good-bye, authz: guest }

/about:                                { controller: default, action: page, args: [ $1 ] }
/terms:                                { controller: default, action: page, args: [ $1 ] }
/contact:              { controller: default, action: contact }

401:                   { controller: auth, action: login-required }
403:                   { controller: error, action: forbidden }
404:                   { controller: error, action: not-found }
500:                   { controller: error, action: error }
