## Routes
---
/:                     { controller: default, action: info }

/event-chains +GET:    { controller: event-chain, action: list }
/event-chains +POST:   { controller: event-chain, action: add }
