## Routes
---
/:                     { controller: default, action: info }

/event-chains:         { controller: event-chain, action: list }
/event-chains/post:    { controller: event-chain, action: add }