locale: en_US
cache: true
debug: false
digest: required
allow_full_reset: !env ALLOW_FULL_RESET

db:
  default:
    client: !env MONGO_DB mongodb://localhost:27017
    database: lto_eventchain

email:
  from: info@legalthings.io
  from_name: Legalthings

lto:
  account: !env LTO_ACCOUNT_SEED_BASE58
