cache: false
display_errors: false

db:
  default:
    client: mongodb://mongo:27017
    database: legalevents

rollbar: false

email:
  From: test@example.com
  FromName: Test
  Mailer: mail

endpoints:
  - schema: "https://specs.livecontracts.io/v0.2.0/scenario/schema.json#"
    url: "http://legalflow/scenarios/"

  - schema: "https://specs.livecontracts.io/v0.2.0/identity/schema.json#"
    url: "http://legalflow/identities/"

  - schema: "https://specs.livecontracts.io/v0.2.0/process/schema.json#"
    url: "http://legalflow/processes/"
    inject_chain: full

  - schema: "https://specs.livecontracts.io/v0.2.0/response/schema.json#"
    url: "http://legalflow/processes/-/response"

triggers:
  - url: "http://legalflow/processes/-/invoke"
    resources:
      - schema: "https://specs.livecontracts.io/v0.2.0/process/schema.json#"
        group:
          process: id
      - schema: "https://specs.livecontracts.io/v0.2.0/response/schema.json#"
        group:
          process: process

queuer: false

anchor: false

environment_variables:
  MONGO_DB: db.default.client
  MONGO_DB_PREFIX: db.default.prefix
  ANCHOR_URL: anchor.url
