debug: true
cache: false

db:
  default:
    client: mongodb://localhost:27017
    database: legalevent

email:
  From: info@example.com
  FromName: Example
  Mailer: mail

endpoints:
  - schema: "https://specs.livecontracts.io/v0.2.0/scenario/schema.json#"
    url: "http://localhost:4001/scenarios/"

  - schema: "https://specs.livecontracts.io/v0.2.0/response/schema.json#"
    url: "http://localhost:4001/processes/-/response"

  - schema: "https://specs.livecontracts.io/v0.2.0/response/schema.json#"
    url: "http://localhost:4001/processes/-/invoke"
    grouped: process

  - schema: "https://specs.livecontracts.io/v0.2.0/identity/schema.json#"
    url: "http://localhost:4001/identities/"

queuer:
  url: http://localhost:3000

anchor:
  url: http://localhost:3001
