debug: true
cache: false

db:
  default:
    client: mongodb://localhost:27017
    database: legalevent

email:
  From: info@example.com
  FromName: Example
  Mailer: mail

endpoints:
  - schema: "https://specs.livecontracts.io/v0.2.0/scenario/schema.json#"
    url: "http://localhost:4001/scenarios/"

  - schema: "https://specs.livecontracts.io/v0.2.0/identity/schema.json#"
    url: "http://localhost:4001/identities/"

  - schema: "https://specs.livecontracts.io/v0.2.0/process/schema.json#"
    url: "http://localhost:4001/processes/"
    inject_chain: full

  - schema: "https://specs.livecontracts.io/v0.2.0/response/schema.json#"
    url: "http://localhost:4001/processes/-/response"

triggers:
  - url: "http://localhost:4001/processes/-/invoke"
    resources:
      - schema: "https://specs.livecontracts.io/v0.2.0/process/schema.json#"
        group:
          process: id
      - schema: "https://specs.livecontracts.io/v0.2.0/response/schema.json#"
        group:
          process: process

queuer: false

anchor: false
