log: browser
debug: true
cache: false
display_errors: false

db:
  default:
    client: mongodb://localhost:27017
    database: legalevent

rollbar: false

email:
  From: info@legalthings.io
  FromName: LegalThings
  Mailer: mail

endpoints:
  "lt:/scenarios/*":      "http://legalflow/scenarios/"
  "lt:/processes/*":      "http://legalflow/responses/"
  "lt:/processes/*/done": "http://legalflow/processes/$2/done"

dispatcher:
  url: http://event-dispatcher
