db:
  default:
    client: mongodb://localhost:27017
    database: legalevent_tests

email:
  From: legalthings@example.com
  FromName: LegalThings
  keep: true
  Mailer: mock

endpoints:
  "lt:/scenarios/*":      "http://legalflow/scenarios/"
  "lt:/processes/*":      "http://legalflow/responses/"
  "lt:/processes/*/done": "http://legalflow/processes/$2/done"

dispatcher:
  url: http://event-dispatcher
