db:
  default:
    client: mongodb://localhost:27017
    database: legalevent_tests

email:
  From: legalthings@example.com
  FromName: LegalThings
  keep: true
  Mailer: mock

endpoints:
  "ltri:/processes/": "http://legalflow.localhost/responses/"
