debug: true
cache: false
digest: optional

db:
  default:
    client: mongodb://localhost:27017
    database: lto_eventchain

mysql:
  dsn: mysql:host=127.0.0.1,dbname=dcigarn
  user: root

email:
  From: info@example.com
  FromName: Example
  Mailer: mail

endpoints:
  - schema: "https://specs.livecontracts.io/v0.2.0/scenario/schema.json#"
    url: "http://localhost:4001/scenarios/"

  - schema: "https://specs.livecontracts.io/v0.2.0/identity/schema.json#"
    url: "http://localhost:4001/identities/"

  - schema: "https://specs.livecontracts.io/v0.2.0/process/schema.json#"
    url: "http://localhost:4001/processes/"
    inject_chain: empty

  - schema: "https://specs.livecontracts.io/v0.2.0/response/schema.json#"
    url: "http://localhost:4001/processes/-/response"

triggers:
  - url: "http://localhost:4001/processes/-/invoke"
    resources:
      - schema: "https://specs.livecontracts.io/v0.2.0/process/schema.json#"
        group:
          process: id
      - schema: "https://specs.livecontracts.io/v0.2.0/response/schema.json#"
        group:
          process: process

lto:
  account:
    sign:
      secretkey: wJ4WH8dD88fSkNdFQRjaAhjFUZzZhV5yiDLDwNUnp6bYwRXrvWV8MJhQ9HL9uqMDG1n7XpTGZx7PafqaayQV8Rp
      publickey: FkU1XyfrCftc4pQKXCrrDyRLSnifX1SMvmx1CYiiyB3Y
    encrypt:
      secretkey: BnjFJJarge15FiqcxrB7Mzt68nseBXXR4LQ54qFBsWJN
      publickey: BVv1ZuE3gKFa6krwWJQwEmrLYUESuUabNCXgYTmCoBt6
