locale: en_US

cache: true
log: true

db:
  default:
    client: mongodb://localhost:27017
    database: lto_eventchain

email:
  from: info@legalthings.io
  from_name: Legalthings

environment_variables:
  MONGO_DB: db.default.client
  ANCHOR_URL: anchor.url
