db:
  default:
    client: mongodb://mongo:27017
    database: lto_eventchain

mysql:
  dsn: mysql:host=mariadb;dbname=dcigarn
  user: root

queuer:
  url: http://event-queuer

anchor:
  url: !env ANCHOR_URL http://anchor

endpoints: []
triggers: []
