db:
  default:
    client: mongodb://localhost:27017
    database: legalevent_tests

email:
  From: legalthings@example.com
  FromName: LegalThings
  keep: true
  Mailer: mock

endpoints:
  "http://specs.livecontracts.io/draft-01/12-response/schema.json#": "http://legalflow.localhost/responses/"
