db:
  default:
    client: !env MONGO_DB mongodb://mongo:27017
    database: lto_eventchain

mysql:
  dsn: !env MYSQL_DSN mysql:host=mariadb;dbname=dcigarn
  username: !env MYSQL_USER
  password: !env MYSQL_PASSWORD

queuer:
  url: http://event-queuer

anchor:
  url: !env ANCHOR_URL http://anchor

endpoints: []
triggers: []
