app:
    name:
    version:

locale: en_EN

cache: true
log: true

db:
  default:
    client: mongodb://localhost:27017
    database: project

email:
    from: info@example.com
    from_name: John Doe

secret:
    signup: 'ENTER SOME RANDOM TEXT HERE'

social:
    facebook:
        client_id:
        client_secret:
    twitter:
        consumer_key:
        consumer_secret:
    google:
        client_id:
        client_secret:
        api_key:
    linkedin:
        client_id:
        client_secret:
