db:
  default:
    client: mongodb://mongo:27017
    database: lto_eventchain

mysql:
  dsn: mysql:host=mariadb;dbname=dcigarn
  username: !env MYSQL_USER
  password: !env MYSQL_PASSWORD

queuer:
  url: http://event-queuer

anchor:
  url: http://anchor

endpoints: []
triggers: []
